name: CD
on: 
  push:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-actions@v1.1.0
        with: 
          username: victorpuntel
          password: $${{ secrets.DOCKER_PASSWORD }}
          repository: victorpuntel/argocd
          tags: ${{ github.sha }}, latest